name: Daily Profile Generation

on:
  schedule:
    # Run daily at 6:00 AM UTC (adjust timezone as needed)
    - cron: "0 6 * * *"
  workflow_dispatch: # Allow manual triggering

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  generate-profile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.16.0"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: "10.12.1"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate AI content via Claude
        uses: anthropics/claude-code-base-action@beta
        with:
          prompt: |
            You are helping generate daily content for a developer's GitHub profile. Generate fresh daily content including:

            1. **ASCII Art Banner** - A simple, clean ASCII art banner related to development, coding, or fantasy themes
            2. **Fantasy Literature Quote** - A meaningful quote from fantasy literature that relates to coding, learning, or personal growth

            ## Requirements

            ### ASCII Art Banner
            - Keep it simple and clean (no complex borders that might break rendering)
            - Should be 1-3 lines maximum
            - Themes: development, coding, fantasy, adventure, learning
            - Examples of good styles:
              - `~ coding adventures daily ~`
              - `[ dev • dad • dumpling ]`
              - `★ fresh code, fresh ideas ★`

            ### Fantasy Literature Quote  
            - Must be from fantasy literature (books, authors like Tolkien, Pratchett, Sanderson, etc.)
            - Should relate to themes of: learning, growth, perseverance, creativity, problem-solving, or adventure
            - Include proper attribution (— Author, Book Title)
            - Avoid quotes already used (check docs/quotes.md if needed)

            ## Output Format

            Please provide the content in this exact format:

            ```
            ASCII_ART: [your ASCII art here]
            QUOTE: [your quote here] — [Author, Book Title]
            ```

            This is for a Principal Engineer at CapitalRx who is a dad, developer, and enjoys fantasy books, RPGs, and bouldering.
          allowed_tools: "View,GlobTool,GrepTool"
          use_node_cache: "true"
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
        env:
          NODE_VERSION: "24.x"
        id: claude-generation

      - name: Generate daily profile
        run: pnpm generate
        env:
          AI_GENERATED_CONTENT: ${{ steps.claude-generation.outputs.result }}

      - name: Commit and push changes
        run: |
          git config --local user.email "devon.wells@pm.me"
          git config --local user.name "devdumpling"
          git add .
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "📅 Daily profile update - $(date +'%Y-%m-%d')"
            git push
          fi
